FROM kalilinux/kali-rolling:latest
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && apt-get -y upgrade && apt-get install --no-install-recommends -y iproute2 net-tools ssh iputils-ping netcat-openbsd curl && apt-get clean && rm -rf /var/lib/apt/lists/*