FROM ubuntu:22.10
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
COPY ./pivotool.sh /pivotool.sh
RUN apt-get update && apt-get install --no-install-recommends openssh-server iputils-ping netcat-openbsd iproute2 sudo -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN useradd -rm -d /home/test -s /bin/bash -g root -G sudo -u 1000 pivotool && echo 'pivotool:pivotool' | chpasswd && chmod +x ./pivotool.sh && service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]